# Copyright 2024 The MathWorks, Inc.

name: Build and Test the "Non-Interactive" Dockerfile

# Trigger this workflow either manually or when a new change is pushed to the
# repo (except .md files)
on:
  workflow_dispatch:
  push:
    # Trigger the workflow when the Dockerfile or any file under tests/ is modified
    paths:
      - "alternates/non-interactive/Dockerfile"
      - "tests/alternates/non-interactive/*"
      - "tests/utils/**"
      - "!**.md"
  schedule:
    # Run at 00:00 on every Monday (1st Day of the Week)
    - cron: "0 0 * * 1"

env:
  IMAGE_BASE_NAME: matlab-non-interactive
  ALT_PATH: alternates/non-interactive

jobs:
  build-test-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        matlab-release: [r2024a, r2023b, r2023a, r2022b, r2022a, r2021b, r2021a, r2020b]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image locally
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          context: ${{ env.ALT_PATH }}
          load: true
          build-args: |
            MATLAB_RELEASE=${{ matrix.matlab-release }}
          tags: |
            ${{ env.IMAGE_BASE_NAME }}:${{ matrix.matlab-release }}

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f tests/requirements.txt ]; then pip install -r tests/requirements.txt; fi

      - name: Test container
        working-directory: tests
        env:
          IMAGE_NAME: ${{ env.IMAGE_BASE_NAME }}:${{ matrix.matlab-release }}
          BATCH_TOKEN: ${{ secrets.MATLAB_BATCH_TOKEN_EXPIRES_03_2025 }}
        run: |
          python -m unittest ${{ env.ALT_PATH }}/test_matlabbatch.py
